### ISSUE TITLE
MRIQC roadmap (m1-4)

### ISSUE THREAD

**Issue by esavary** [nipreps/mriqc#1052]
- [x] Fully remove dependency on FOSS components with commercial restrictions (i.e., FSL)
- [x] Integration of new telemetry system
- [x] Integration of new NiReports component

**Comment by oesteban** [comment]
Let's follow the FSL-stripping on #1032.
