### ISSUE TITLE
Review NMIND Checklist submitted and provide corrections if desired

### ISSUE THREAD

**Issue by LuciMoore** [nipreps/mriqc#1362]
### What would you like to see added in this software?

I've submitted an [NMIND checklist](https://www.nmind.org/standards-checklist/) for MRIQC [here](https://github.com/nmind/proceedings/issues/27) and it is waiting for final review by the NMIND team in order to be added to the NMIND list of [Evaluated Tools](https://www.nmind.org/proceedings/). This was done as part of the [software & analytic standards outlined for pipelines/tools](https://hbcd-docs.readthedocs.io/en/latest/processing/standards/) utilized for the HBCD data release and the tools are expected to undergo final review and approval by Dec 10th. 

Please feel free to review the checklist and let me know if you feel I've missed anything. You can view the checklist by creating a file copy of the json posted to the issue and importing it into the checklist by clicking IMPORT JSON at the bottom of the [checklist page](https://www.nmind.org/standards-checklist/). If you noticed that I missed something, you can either revise the checklist json within the issue or just let me know directly which items should be checked as complete

For quick reference, I determined that all checklist items were complete except the following:

**Gold Badge checklist items for Documentation:**

- [ ] Continuous integration badges in README for coverage
- [ ] Maintenance status is documented
(e.g., expected turnaround time on pull requests, whether project is maintained)

**Bronze, Silver, and Gold Checklists items for Testing:**

Bronze:

- [ ] Provide / generate / point to test data

- [ ] Provide instructions for users to run tests that include instructions for evaluation for correct behavior

Silver:

- [ ] Some form of testing suite present
- [ ] Test coverage > 50%

Gold:

- [ ] Test coverage > 90%
- [ ] Benchmarking information is provided for examples

I've posted this issue for your general awareness just in case you wanted to review the checklist for errors (although these will likely be caught by the final NMIND review as well), you can close it whenever you would like. Thank you!

### Do you have any interest in helping implement the feature?

Yes
